import { StrictMode, useCallback, useEffect, useMemo, useState } from "react";
import { createRoot } from "react-dom/client";
import { Activity, AlertCircle, Archive, ChevronRight, Clock3, Copy, Database, Download, Eye, EyeOff, FileKey2, Filter, Laptop, LogOut, Menu, Pause, Play, RefreshCw, Search, Server, ShieldCheck, Smartphone, Terminal, Trash2, Wifi, X } from "lucide-react";
import "./styles.css";
import { formatBytes, formatDate, formatTime } from "./utils";

type Flow = {
  id: string; captureId: string; sessionId: string; protocol: string; method?: string; host: string; path?: string;
  status?: number; requestContentType?: string; responseContentType?: string; requestBytes: number; responseBytes: number;
  startedAt: string; completedAt?: string; durationMs?: number; state: "loading" | "complete" | "error"; errorCode?: string;
  notCapturedReason?: string; websocket?: boolean;
};
type FlowDetail = Flow & { raw: boolean; url: string; query: string[][]; requestHeaders: string[][]; responseHeaders: string[][] };
type BodyPreview = { state: string; encoding: string; content: string; contentType?: string; view: string; raw: boolean; truncated: boolean };

const methodColors: Record<string, string> = { GET: "green", POST: "purple", PUT: "orange", PATCH: "orange", DELETE: "red", CONNECT: "blue" };
const api = {
  async request<T>(path: string, init: RequestInit = {}): Promise<T> {
    const headers = new Headers(init.headers);
    if (init.body && !headers.has("content-type")) headers.set("content-type", "application/json");
    if (!['GET', 'HEAD'].includes(init.method || 'GET')) {
      const csrf = document.cookie.split(";").map((part) => part.trim()).find((part) => part.startsWith("mti_csrf="))?.split("=")[1];
      if (csrf) headers.set("X-CSRF-Token", decodeURIComponent(csrf));
    }
    const response = await fetch(path, { ...init, headers, credentials: "include" });
    if (!response.ok) {
      if (response.status === 401) window.dispatchEvent(new Event("mti:unauthenticated"));
      const detail = await response.json().catch(() => ({}));
      throw new Error(detail.detail || `Request failed (${response.status})`);
    }
    if (response.status === 204) return undefined as T;
    return response.json() as Promise<T>;
  },
  flows: (query = "") => api.request<{ items: Flow[] }>(`/api/flows${query}`),
  flow: (id: string, token?: string) => api.request<FlowDetail>(`/api/flows/${id}`, token ? { headers: { "X-Reveal-Token": token } } : {}),
  body: (id: string, direction: string, token?: string) => api.request<BodyPreview>(`/api/flows/${id}/body/${direction}`, token ? { headers: { "X-Reveal-Token": token } } : {}),
  sessions: () => api.request<any[]>("/api/sessions"),
  devices: () => api.request<any[]>("/api/devices"),
  system: () => api.request<any>("/api/system"),
  audit: () => api.request<any[]>("/api/audit")
};

function Login({ onLogin }: { onLogin: () => void }) {
  const [password, setPassword] = useState(""); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  async function submit(event: React.FormEvent) {
    event.preventDefault(); setBusy(true); setError("");
    try { await api.request("/auth/login", { method: "POST", body: JSON.stringify({ username: "admin", password }) }); onLogin(); }
    catch (err) { setError(err instanceof Error ? err.message : "Login failed"); } finally { setBusy(false); }
  }
  return <main className="login-page"><section className="login-card"><div className="brand-mark"><ShieldCheck size={26} /></div><p className="eyebrow">SELF-HOSTED OPERATIONS</p><h1>Mobile Traffic Inspector</h1><p className="muted">Sign in to inspect authorized device traffic.</p><form onSubmit={submit}><label>Admin password<input autoFocus type="password" value={password} onChange={(e) => setPassword(e.target.value)} minLength={12} required /></label>{error && <p className="error-text"><AlertCircle size={15} />{error}</p>}<button className="primary full" disabled={busy}>{busy ? "Checking…" : "Sign in"}</button></form><p className="footnote">Access is audited. Raw body reveal expires after 60 seconds.</p></section></main>;
}

function AppShell({ onLogout }: { onLogout: () => void }) {
  const [page, setPage] = useState("live"); const [mobileNav, setMobileNav] = useState(false);
  const nav = [{ id: "live", label: "Live Capture", icon: Activity }, { id: "sessions", label: "Sessions", icon: Archive }, { id: "devices", label: "Devices / Setup", icon: Smartphone }, { id: "system", label: "System / Audit", icon: Server }];
  return <div className="app-shell"><aside className={mobileNav ? "sidebar open" : "sidebar"}><div className="sidebar-brand"><div className="brand-mark small"><ShieldCheck size={19} /></div><span>traffic<span className="brand-accent">/</span>inspector</span></div><nav>{nav.map(({ id, label, icon: Icon }) => <button key={id} className={page === id ? "nav-item active" : "nav-item"} onClick={() => { setPage(id); setMobileNav(false); }}><Icon size={17} />{label}</button>)}</nav><div className="sidebar-bottom"><div className="connection-status"><span className="pulse-dot" />Capture online</div><button className="nav-item" onClick={onLogout}><LogOut size={17} />Sign out</button></div></aside><div className="main-column"><header className="topbar"><button className="icon-button menu-button" onClick={() => setMobileNav(!mobileNav)} aria-label="Toggle navigation"><Menu size={21} /></button><div className="breadcrumbs"><span>Operations</span><ChevronRight size={14} /><strong>{nav.find((item) => item.id === page)?.label}</strong></div><div className="topbar-actions"><span className="secure-chip"><ShieldCheck size={14} />Encrypted at rest</span><button className="icon-button" onClick={() => window.location.reload()} aria-label="Refresh"><RefreshCw size={17} /></button></div></header><main className="content">{page === "live" && <LiveCapture />}{page === "sessions" && <Sessions />}{page === "devices" && <Devices />}{page === "system" && <SystemAudit />}</main></div></div>;
}

function LiveCapture() {
  const [flows, setFlows] = useState<Flow[]>([]); const [selected, setSelected] = useState<string>(); const [query, setQuery] = useState(""); const [paused, setPaused] = useState(false); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  const refresh = useCallback(async () => { try { const result = await api.flows(query ? `?q=${encodeURIComponent(query)}` : ""); setFlows(result.items); setError(""); } catch (err) { setError(err instanceof Error ? err.message : "Unable to load capture"); } finally { setLoading(false); } }, [query]);
  useEffect(() => { void refresh(); const timer = window.setInterval(() => void refresh(), 5000); return () => window.clearInterval(timer); }, [refresh]);
  useEffect(() => { const protocol = location.protocol === "https:" ? "wss:" : "ws:"; const socket = new WebSocket(`${protocol}//${location.host}/ws/live`); socket.onmessage = (event) => { const payload = JSON.parse(event.data); if (payload.type?.startsWith("flow.")) setFlows((current) => { const flow = payload.flow as Flow; const index = current.findIndex((item) => item.id === flow.id); if (index < 0) return [flow, ...current].slice(0, 500); const next = [...current]; next[index] = { ...next[index], ...flow }; return next; }); }; return () => socket.close(); }, []);
  async function togglePause() { try { await api.request("/api/system/pause", { method: "PUT", body: JSON.stringify({ paused: !paused }) }); setPaused(!paused); } catch (err) { setError(err instanceof Error ? err.message : "Unable to change capture state"); } }
  return <div className="page-grid"><section className="panel master-panel"><div className="page-heading"><div><p className="eyebrow">REAL-TIME FEED</p><h1>Live Capture</h1><p className="muted">Every enrolled device · raw traffic retained until deleted</p></div><div className="heading-actions"><button className={paused ? "secondary pause-on" : "secondary"} onClick={togglePause}>{paused ? <Play size={15} /> : <Pause size={15} />}{paused ? "Resume" : "Pause recording"}</button><span className="live-chip"><span className="pulse-dot" />LIVE</span></div></div><div className="toolbar"><div className="search-box"><Search size={16} /><input placeholder="Search host or path…" value={query} onChange={(e) => setQuery(e.target.value)} /><kbd>⌘ K</kbd></div><button className="filter-button"><Filter size={15} />Filters</button><span className="result-count">{flows.length} flows</span></div>{error && <div className="inline-error"><AlertCircle size={15} />{error}<button onClick={() => void refresh}>Retry</button></div>}{loading ? <EmptyState icon={<RefreshCw className="spin" />} title="Loading capture" detail="Connecting to the encrypted event stream…" /> : flows.length === 0 ? <EmptyState icon={<Wifi />} title="No traffic yet" detail="Connect a registered WireGuard device to begin capturing." /> : <div className="flow-table" role="table" aria-label="Captured flows"><div className="flow-row flow-header" role="row"><span>Method / host</span><span>Status</span><span>Type</span><span>Time</span><span /></div>{flows.map((flow) => <button className={selected === flow.id ? "flow-row selected" : "flow-row"} key={flow.id} onClick={() => setSelected(flow.id)}><span className="flow-main"><span className={`method ${methodColors[flow.method || ""] || "gray"}`}>{flow.method || flow.protocol}</span><span className="host-path"><strong>{flow.host}</strong><small>{flow.path || "—"}</small></span></span><span className={`status status-${flow.state}`}>{flow.state === "loading" ? <span className="loading-dot" /> : flow.status || "ERR"}</span><span className="content-type">{flow.responseContentType || flow.requestContentType || "—"}</span><span className="flow-time">{formatTime(flow.startedAt)}</span><ChevronRight size={15} className="row-chevron" /></button>)}</div>}</section>{selected ? <FlowDetailPanel flowId={selected} onClose={() => setSelected(undefined)} /> : <section className="panel detail-placeholder"><div className="placeholder-art"><Eye size={30} /></div><h2>Select a flow</h2><p className="muted">Choose a request from the feed to inspect headers, body, timing and WebSocket messages.</p><div className="key-hint"><kbd>↑</kbd><kbd>↓</kbd> navigate <kbd>Enter</kbd> inspect</div></section>}</div>;
}

function FlowDetailPanel({ flowId, onClose }: { flowId: string; onClose: () => void }) {
  const [detail, setDetail] = useState<FlowDetail>(); const [tab, setTab] = useState("request"); const [error, setError] = useState(""); const [revealToken, setRevealToken] = useState<string>(); const [reauthOpen, setReauthOpen] = useState(false);
  useEffect(() => { setDetail(undefined); setRevealToken(undefined); void api.flow(flowId).then(setDetail).catch((err) => setError(err.message)); }, [flowId]);
  async function reveal(password: string) { const result = await api.request<{ token: string }>(`/api/flows/${flowId}/reveal`, { method: "POST", body: JSON.stringify({ password }) }); setRevealToken(result.token); setReauthOpen(false); setTimeout(() => setRevealToken(undefined), 60000); setDetail(await api.flow(flowId, result.token)); }
  return <section className="panel detail-panel">{reauthOpen && <ReauthDialog onCancel={() => setReauthOpen(false)} onSubmit={reveal} />}{!detail ? <EmptyState icon={<RefreshCw className="spin" />} title="Loading flow" detail={error || "Fetching encrypted metadata…"} /> : <><div className="detail-head"><div><div className="detail-route"><span className={`method ${methodColors[detail.method || ""] || "gray"}`}>{detail.method || detail.protocol}</span><h2>{detail.host}</h2></div><p className="detail-path">{detail.path || "—"}</p></div><div className="detail-actions"><button className="icon-button" onClick={onClose} aria-label="Close detail"><X size={17} /></button></div></div><div className="detail-status"><span className={`status status-${detail.state}`}>{detail.status || detail.state}</span><span>{detail.durationMs ? `${detail.durationMs} ms` : "Timing pending"}</span><span>{formatBytes(detail.requestBytes + detail.responseBytes)} transferred</span>{detail.raw ? <span className="raw-chip"><Eye size={13} />Raw reveal active</span> : <button className="reveal-button" onClick={() => setReauthOpen(true)}><Eye size={13} />Reveal secrets</button>}</div><div className="tabs" role="tablist">{["request", "response", "timing", "websocket"].map((item) => <button role="tab" aria-selected={tab === item} className={tab === item ? "tab active" : "tab"} key={item} onClick={() => setTab(item)}>{item === "websocket" ? "WebSocket" : item[0].toUpperCase() + item.slice(1)}</button>)}</div>{tab === "request" && <MessageView direction="request" detail={detail} token={revealToken} />}{tab === "response" && <MessageView direction="response" detail={detail} token={revealToken} />}{tab === "timing" && <TimingView detail={detail} />}{tab === "websocket" && <WebSocketView flowId={flowId} />}</>}</section>;
}

function MessageView({ direction, detail, token }: { direction: "request" | "response"; detail: FlowDetail; token?: string }) { const [body, setBody] = useState<BodyPreview>(); useEffect(() => { void api.body(detail.id, direction, token).then(setBody).catch(() => setBody({ state: "error", encoding: "", content: "", view: "text", raw: false, truncated: false })); }, [detail.id, direction, token]); const headers = direction === "request" ? detail.requestHeaders : detail.responseHeaders; return <div className="message-view"><InfoLine label="URL" value={detail.url} mono /><InfoLine label="Query" value={detail.query.length ? detail.query.map(([key, value]) => `${key}=${value}`).join("&") : "None"} mono /><div className="subheading">Headers <span>{headers.length}</span></div><HeadersTable headers={headers} /><div className="subheading">Body <span>{body?.truncated ? "preview truncated" : formatBytes(direction === "request" ? detail.requestBytes : detail.responseBytes)}</span></div>{body ? <BodyBox body={body} /> : <div className="body-box loading-box">Loading preview…</div>}</div>; }
function HeadersTable({ headers }: { headers: string[][] }) { return <div className="headers-table">{headers.map(([key, value], index) => <div className="header-line" key={`${key}-${index}`}><span>{key}</span><code>{value}</code></div>)}</div>; }
function InfoLine({ label, value, mono }: { label: string; value: string; mono?: boolean }) { return <div className="info-line"><span>{label}</span><code className={mono ? "mono" : ""}>{value}</code></div>; }
function BodyBox({ body }: { body: BodyPreview }) { const [showRaw, setShowRaw] = useState(false); let text = ""; try { text = atob(body.content); if (body.view === "json" && !showRaw) text = JSON.stringify(JSON.parse(text), null, 2); } catch { text = "Binary content"; } return <div className="body-box"><div className="body-toolbar"><span className="badge">{body.view}</span>{body.raw && <button onClick={() => setShowRaw(!showRaw)}>{showRaw ? <EyeOff size={14} /> : <Eye size={14} />}{showRaw ? "Hide" : "Show"}</button>}{body.state === "truncated" && <span className="warning">Preview limited</span>}</div>{body.state === "not-captured" ? <span className="muted">Body not captured for this flow.</span> : body.state === "error" ? <span className="error-text">Unable to decrypt body from storage.</span> : <pre>{text}</pre>}</div>; }
function TimingView({ detail }: { detail: FlowDetail }) { return <div className="timing-view"><div className="timing-card"><Clock3 size={18} /><div><span>Total duration</span><strong>{detail.durationMs ? `${detail.durationMs} ms` : "Pending"}</strong></div></div><div className="timeline"><div className="timeline-row"><span>Client → proxy</span><div className="bar"><i style={{ width: "12%" }} /></div><b>2 ms</b></div><div className="timeline-row"><span>Proxy → server</span><div className="bar"><i style={{ width: "52%" }} /></div><b>{detail.durationMs ? `${Math.max(1, Math.floor(detail.durationMs * .52))} ms` : "—"}</b></div><div className="timeline-row"><span>Server → proxy</span><div className="bar"><i style={{ width: "36%" }} /></div><b>{detail.durationMs ? `${Math.max(1, Math.floor(detail.durationMs * .36))} ms` : "—"}</b></div></div></div>; }
function WebSocketView({ flowId }: { flowId: string }) { return <div className="empty-inline"><Terminal size={19} /><p>WebSocket messages for this flow will appear here as the connection is active.</p><small>Flow ID {flowId.slice(0, 12)}…</small></div>; }
function ReauthDialog({ onCancel, onSubmit }: { onCancel: () => void; onSubmit: (password: string) => Promise<void> }) { const [password, setPassword] = useState(""); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); async function submit(event: React.FormEvent) { event.preventDefault(); setBusy(true); try { await onSubmit(password); } catch (err) { setError(err instanceof Error ? err.message : "Unable to reveal"); } finally { setBusy(false); } } return <div className="modal-backdrop"><form className="reauth-dialog" onSubmit={submit}><button type="button" className="icon-button close-modal" onClick={onCancel}><X size={17} /></button><div className="brand-mark small"><Eye size={18} /></div><h2>Reveal sensitive data?</h2><p className="muted">This action is audited and the temporary reveal closes after 60 seconds.</p><label>Confirm admin password<input type="password" value={password} onChange={(e) => setPassword(e.target.value)} required autoFocus /></label>{error && <p className="error-text">{error}</p>}<div className="dialog-actions"><button type="button" className="secondary" onClick={onCancel}>Cancel</button><button className="primary" disabled={busy}>{busy ? "Verifying…" : "Reveal for 60s"}</button></div></form></div>; }
function Sessions() { const [rows, setRows] = useState<any[]>([]); useEffect(() => { void api.sessions().then(setRows).catch(() => setRows([])); }, []); return <Page title="Sessions" eyebrow="CAPTURE ARCHIVE" detail="Browse retained sessions and manage storage intentionally."><div className="panel table-panel"><div className="table-heading"><h2>Retained sessions</h2><button className="secondary" onClick={() => void api.sessions().then(setRows)}><RefreshCw size={15} />Refresh</button></div><div className="simple-table"><div className="simple-row header"><span>Session</span><span>Started</span><span>Flows</span><span>Body volume</span><span /></div>{rows.length ? rows.map((row) => <div className="simple-row" key={row.id}><span><strong>{row.name}</strong><small>{row.id.slice(0, 12)}…</small></span><span>{formatDate(row.startedAt)}</span><span>{row.flowCount}</span><span>{formatBytes(row.bytes)}</span><button className="icon-button danger" aria-label="Delete session"><Trash2 size={16} /></button></div>) : <EmptyState icon={<Archive />} title="No sessions" detail="Sessions appear when the first enrolled device connects." />}</div></div></Page>; }
function Devices() { const [rows, setRows] = useState<any[]>([]); useEffect(() => { void api.devices().then(setRows).catch(() => setRows([])); }, []); return <Page title="Devices / Setup" eyebrow="AUTHORIZED PEERS" detail="Register WireGuard peers and verify the inspection trust chain."><div className="split-cards"><section className="panel setup-card"><div className="card-icon"><FileKey2 size={19} /></div><h2>Connect a device</h2><p className="muted">Generate the client profile from the capture container, then import it into WireGuard on iOS or Android.</p><ol className="setup-steps"><li><span>01</span><code>docker compose cp capture:/home/mitmproxy/.mitmproxy/wireguard.conf ./device.conf</code></li><li><span>02</span><span>Import <strong>device.conf</strong> into WireGuard and activate the tunnel.</span></li><li><span>03</span><span>Install the <a href="/setup/mitmproxy-ca-cert.pem">public CA certificate</a>, then enable trust for debug builds.</span></li></ol><div className="callout"><ShieldCheck size={16} /><span>Never upload the WireGuard config or CA private key to this panel.</span></div></section><section className="panel setup-card"><div className="card-icon green-bg"><Smartphone size={19} /></div><h2>Registered peers</h2>{rows.length ? <div className="device-list">{rows.map((row) => <div className="device-row" key={row.id}><div className="device-avatar"><Smartphone size={15} /></div><div><strong>{row.name}</strong><small>{row.tunnelIp || "Tunnel address pending"}</small></div><span className={row.revokedAt ? "status status-error" : "status status-complete"}>{row.revokedAt ? "Revoked" : "Active"}</span></div>)}</div> : <div className="empty-inline"><Laptop size={20} /><p>No peers registered yet.</p></div>}</section></div></Page>; }
function SystemAudit() { const [system, setSystem] = useState<any>(); const [audit, setAudit] = useState<any[]>([]); useEffect(() => { void Promise.all([api.system(), api.audit()]).then(([s, a]) => { setSystem(s); setAudit(a); }).catch(() => undefined); }, []); return <Page title="System / Audit" eyebrow="OPERATIONS" detail="Storage, ingest health and sensitive-action audit trail."><div className="metrics-grid">{[[Database, "Recorded body", formatBytes(system?.recordedBodyBytes || 0)], [Server, "Disk free", formatBytes(system?.disk?.free || 0)], [Activity, "Spooled events", system?.spooledEvents || 0], [AlertCircle, "Dropped events", system?.droppedEvents || 0]].map(([Icon, label, value]) => <div className="metric-card" key={String(label)}><Icon size={18} /><span>{label}</span><strong>{value}</strong></div>)}</div><section className="panel table-panel"><div className="table-heading"><div><h2>Audit trail</h2><p className="muted">Raw reveal, export and device actions are recorded.</p></div><button className="secondary" onClick={() => void api.audit().then(setAudit)}><RefreshCw size={15} />Refresh</button></div><div className="simple-table audit-table"><div className="simple-row header"><span>Action</span><span>Target</span><span>Source</span><span>Time</span></div>{audit.length ? audit.map((row) => <div className="simple-row" key={row.id}><span><strong>{row.action}</strong></span><span>{row.targetType ? `${row.targetType} ${row.targetId?.slice(0, 10) || ""}` : "—"}</span><span>{row.sourceIp || "—"}</span><span>{formatDate(row.createdAt)}</span></div>) : <EmptyState icon={<ShieldCheck />} title="Audit is clean" detail="Sensitive actions will appear here." />}</div></section></Page>; }
function Page({ title, eyebrow, detail, children }: { title: string; eyebrow: string; detail: string; children: React.ReactNode }) { return <div className="page"><div className="page-heading"><div><p className="eyebrow">{eyebrow}</p><h1>{title}</h1><p className="muted">{detail}</p></div></div>{children}</div>; }
function EmptyState({ icon, title, detail }: { icon: React.ReactNode; title: string; detail: string }) { return <div className="empty-state"><div className="empty-icon">{icon}</div><h2>{title}</h2><p className="muted">{detail}</p></div>; }

function Root() { const [authenticated, setAuthenticated] = useState<boolean | undefined>(); useEffect(() => { const handler = () => setAuthenticated(false); window.addEventListener("mti:unauthenticated", handler); void api.request("/auth/me").then(() => setAuthenticated(true)).catch(() => setAuthenticated(false)); return () => window.removeEventListener("mti:unauthenticated", handler); }, []); if (authenticated === undefined) return <div className="splash"><ShieldCheck className="spin" size={26} />Loading secure workspace…</div>; return authenticated ? <AppShell onLogout={() => { void api.request("/auth/logout", { method: "POST" }).finally(() => setAuthenticated(false)); }} /> : <Login onLogin={() => setAuthenticated(true)} />; }

createRoot(document.getElementById("root")!).render(<StrictMode><Root /></StrictMode>);
